### ISSUE TITLE
Installing chaincodes problem

### ISSUE THREAD

**Issue by umegbewe** [kfsoftware/hlf-operator#100]
Hello,

I'm trying to install a javascript chaincode directly with the following command:
```
kubectl hlf chaincode install --path=./chaincode/fabcar/go \
    --config=org.yaml --language=node --label=label --user=admin --peer=default
```
and it gives the error:
```
Chaincode status Code: (500) UNKNOWN. Description: failed to invoke backing implementation of 'InstallChaincode':
could not build chaincode: docker build failed: docker build is disabled                                               
```
I'm running the operator version 1.6.0 and the plugin version 1.6.4 on a kind cluster, I also tried the operator version 1.6.1 and 1.5.0 and even a golang chaincode but same error.

**Comment by dviejokfs** [comment]
Hey @umegbewe 
You need to use 
In order to create the peer with the external builder built int you can use the flag `--k8s-builder` when creating the peer.

The image you should be using is the following in order to have the external builder already bundled into the docker image:
```bash
export PEER_IMAGE=quay.io/kfsoftware/fabric-peer
export PEER_VERSION=2.4.1-v0.0.3
```

**Comment by umegbewe** [comment]
@dviejokfs Thanks for the response

I tried this out on kind and minikube, same error.

command:
```
kubectl hlf peer create --image=$PEER_IMAGE --version=$PEER_VERSION --storage-class=$STORAGE_CLASS --enroll-id=peer --mspid=$MSP_ORG \
        --enroll-pw=$PEER_SECRET --capacity=5Gi --name=$ORG-peer1 --ca-name=$ORG-ca.$NAMESPACE --k8s-builder=true
```
