### ISSUE TITLE
Feature request: adding CA "attributes" to user registration

### ISSUE THREAD

**Issue by mobycrypt** [kfsoftware/hlf-operator#101]
Currently there is no possibility to add attributes to user on registration with `kubectl hlf ca register` command. Because of that it's not for example possible to register user which will have possibility to register other users (it would require `hf.Registrar.Roles: "*"` attribute). 

It would be great to add such possibility.

**Comment by dviejokfs** [comment]
@PeerZetZzZzZ  Added in 1.7.0
