### ISSUE TITLE
notifyRegistry -> failed to start <chaincode_name> -- peer will not accept external chaincode connection <chaincode_name> (except in dev mode)

### ISSUE THREAD

**Issue by anzalbeg** [kfsoftware/hlf-operator#103]
I am getting the error in peer logs notifyRegistry -> failed to start <chaincode_name>  -- peer will not accept external chaincode connection <chaincode_name> (except in dev mode).  When calling the chaincode invoke after successfully commit, transaction got timed out.

Please check the peers logs ----

[33m2022-07-27 12:06:44.199 UTC 02f6 WARN[0m [endorser] [33;1mProcessProposal[0m -> Failed to invoke chaincode channel=mychannel chaincode=titledeed error="error in simulation: failed to execute transaction b2caff78824cfc000ada9426f8a637512605e4f5fb6499baf985b13461a6f19e: could not launch chaincode titledeed:a65c28bd17770151d83e51e974b553907ffb11a9696fd7269aa8759b162a4707: timeout expired while starting chaincode titledeed:a65c28bd17770151d83e51e974b553907ffb11a9696fd7269aa8759b162a4707 for transaction"
[34m2022-07-27 12:06:44.199 UTC 02f7 INFO[0m [comm.grpc.server] [34;1m1[0m -> unary call completed grpc.service=protos.Endorser grpc.method=ProcessProposal grpc.request_deadline=2022-07-27T12:04:44.187Z grpc.peer_address=10.244.0.1:39906 grpc.code=OK grpc.call_duration=5m0.003947359s
[34m2022-07-27 12:06:56.770 UTC 02f8 INFO[0m [endorser] [34;1mcallChaincode[0m -> finished chaincode: cscc duration: 0ms channel=mychannel txID=7b98a76b
[34m2022-07-27 12:06:56.770 UTC 02f9 INFO[0m [comm.grpc.server] [34;1m1[0m -> unary call completed grpc.service=protos.Endorser grpc.method=ProcessProposal grpc.request_deadline=2022-07-27T12:09:56.765Z grpc.peer_address=10.244.0.1:7094 grpc.code=OK grpc.call_duration=1.598366ms
[31m2022-07-27 12:06:56.785 UTC 02fa ERRO[0m [chaincode] [31;1mnotifyRegistry[0m -> failed to start titledeed -- peer will not accept external chaincode connection titledeed (except in dev mode)
[34m2022-07-27 12:11:56.775 UTC 02fb INFO[0m [endorser] [34;1mcallChaincode[0m -> finished chaincode: titledeed duration: 300000ms channel=mychannel txID=0bafb81e
[31m2022-07-27 12:11:56.776 UTC 02fc ERRO[0m [endorser] [31;1msimulateProposal[0m -> failed to invoke chaincode titledeed, error: timeout expired while starting chaincode titledeed:a65c28bd17770151d83e51e974b553907ffb11a9696fd7269aa8759b162a4707 for transaction
github.com/hyperledger/fabric/core/chaincode.(*RuntimeLauncher).Launch
	/go/src/github.com/hyperledger/fabric/core/chaincode/runtime_launcher.go:130
github.com/hyperledger/fabric/core/chaincode.(*ChaincodeSupport).Launch
	/go/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:86
github.com/hyperledger/fabric/core/chaincode.(*ChaincodeSupport).Invoke
	/go/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:203
github.com/hyperledger/fabric/core/chaincode.(*ChaincodeSupport).Execute
	/go/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:161
github.com/hyperledger/fabric/core/endorser.(*SupportImpl).Execute
	/go/src/github.com/hyperledger/fabric/core/endorser/support.go:126
github.com/hyperledger/fabric/core/endorser.(*Endorser).callChaincode
	/go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:120
github.com/hyperledger/fabric/core/endorser.(*Endorser).simulateProposal
	/go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:187
github.com/hyperledger/fabric/core/endorser.(*Endorser).ProcessProposalSuccessfullyOrError
	/go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:409
github.com/hyperledger/fabric/core/endorser.(*Endorser).ProcessProposal
	/go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:350
github.com/hyperledger/fabric/core/handlers/auth/filter.(*expirationCheckFilter).ProcessProposal
	/go/src/github.com/hyperledger/fabric/core/handlers/auth/filter/expiration.go:61
github.com/hyperledger/fabric/core/handlers/auth/filter.(*filter).ProcessProposal
	/go/src/github.com/hyperledger/fabric/core/handlers/auth/filter/filter.go:32
github.com/hyperledger/fabric-protos-go/peer._Endorser_ProcessProposal_Handler.func1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/hyperledger/fabric-protos-go/peer/peer.pb.go:107
github.com/hyperledger/fabric/internal/peer/node.unaryGrpcLimiter.func1
	/go/src/github.com/hyperledger/fabric/internal/peer/node/grpc_limiters.go:56
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25
github.com/hyperledger/fabric/common/grpclogging.UnaryServerInterceptor.func1
	/go/src/github.com/hyperledger/fabric/common/grpclogging/server.go:92
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25
github.com/hyperledger/fabric/common/grpcmetrics.UnaryServerInterceptor.func1
	/go/src/github.com/hyperledger/fabric/common/grpcmetrics/interceptor.go:31
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34
github.com/hyperledger/fabric-protos-go/peer._Endorser_ProcessProposal_Handler
	/go/src/github.com/hyperledger/fabric/vendor/github.com/hyperledger/fabric-protos-go/peer/peer.pb.go:109
google.golang.org/grpc.(*Server).processUnaryRPC
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:1180
google.golang.org/grpc.(*Server).handleStream
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:1503
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:843
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
could not launch chaincode titledeed:a65c28bd17770151d83e51e974b553907ffb11a9696fd7269aa8759b162a4707
github.com/hyperledger/fabric/core/chaincode.(*ChaincodeSupport).Launch
	/go/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:87
github.com/hyperledger/fabric/core/chaincode.(*ChaincodeSupport).Invoke
	/go/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:203
github.com/hyperledger/fabric/core/chaincode.(*ChaincodeSupport).Execute
	/go/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:161
github.com/hyperledger/fabric/core/endorser.(*SupportImpl).Execute
	/go/src/github.com/hyperledger/fabric/core/endorser/support.go:126
github.com/hyperledger/fabric/core/endorser.(*Endorser).callChaincode
	/go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:120
github.com/hyperledger/fabric/core/endorser.(*Endorser).simulateProposal
	/go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:187
github.com/hyperledger/fabric/core/endorser.(*Endorser).ProcessProposalSuccessfullyOrError
	/go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:409
github.com/hyperledger/fabric/core/endorser.(*Endorser).ProcessProposal
	/go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:350
github.com/hyperledger/fabric/core/handlers/auth/filter.(*expirationCheckFilter).ProcessProposal
	/go/src/github.com/hyperledger/fabric/core/handlers/auth/filter/expiration.go:61
github.com/hyperledger/fabric/core/handlers/auth/filter.(*filter).ProcessProposal
	/go/src/github.com/hyperledger/fabric/core/handlers/auth/filter/filter.go:32
github.com/hyperledger/fabric-protos-go/peer._Endorser_ProcessProposal_Handler.func1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/hyperledger/fabric-protos-go/peer/peer.pb.go:107
github.com/hyperledger/fabric/internal/peer/node.unaryGrpcLimiter.func1
	/go/src/github.com/hyperledger/fabric/internal/peer/node/grpc_limiters.go:56
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25
github.com/hyperledger/fabric/common/grpclogging.UnaryServerInterceptor.func1
	/go/src/github.com/hyperledger/fabric/common/grpclogging/server.go:92
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25
github.com/hyperledger/fabric/common/grpcmetrics.UnaryServerInterceptor.func1
	/go/src/github.com/hyperledger/fabric/common/grpcmetrics/interceptor.go:31
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34
github.com/hyperledger/fabric-protos-go/peer._Endorser_ProcessProposal_Handler
	/go/src/github.com/hyperledger/fabric/vendor/github.com/hyperledger/fabric-protos-go/peer/peer.pb.go:109
google.golang.org/grpc.(*Server).processUnaryRPC
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:1180
google.golang.org/grpc.(*Server).handleStream
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:1503
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:843
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
failed to execute transaction 0bafb81e0b026767513a885afc3d87c57925df013c7532bbacdb75c056fbd1e2
github.com/hyperledger/fabric/core/chaincode.processChaincodeExecutionResult
	/go/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:167
github.com/hyperledger/fabric/core/chaincode.(*ChaincodeSupport).Execute
	/go/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:162
github.com/hyperledger/fabric/core/endorser.(*SupportImpl).Execute
	/go/src/github.com/hyperledger/fabric/core/endorser/support.go:126
github.com/hyperledger/fabric/core/endorser.(*Endorser).callChaincode
	/go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:120
github.com/hyperledger/fabric/core/endorser.(*Endorser).simulateProposal
	/go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:187
github.com/hyperledger/fabric/core/endorser.(*Endorser).ProcessProposalSuccessfullyOrError
	/go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:409
github.com/hyperledger/fabric/core/endorser.(*Endorser).ProcessProposal
	/go/src/github.com/hyperledger/fabric/core/endorser/endorser.go:350
github.com/hyperledger/fabric/core/handlers/auth/filter.(*expirationCheckFilter).ProcessProposal
	/go/src/github.com/hyperledger/fabric/core/handlers/auth/filter/expiration.go:61
github.com/hyperledger/fabric/core/handlers/auth/filter.(*filter).ProcessProposal
	/go/src/github.com/hyperledger/fabric/core/handlers/auth/filter/filter.go:32
github.com/hyperledger/fabric-protos-go/peer._Endorser_ProcessProposal_Handler.func1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/hyperledger/fabric-protos-go/peer/peer.pb.go:107
github.com/hyperledger/fabric/internal/peer/node.unaryGrpcLimiter.func1
	/go/src/github.com/hyperledger/fabric/internal/peer/node/grpc_limiters.go:56
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25
github.com/hyperledger/fabric/common/grpclogging.UnaryServerInterceptor.func1
	/go/src/github.com/hyperledger/fabric/common/grpclogging/server.go:92
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25
github.com/hyperledger/fabric/common/grpcmetrics.UnaryServerInterceptor.func1
	/go/src/github.com/hyperledger/fabric/common/grpcmetrics/interceptor.go:31
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
	/go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34
github.com/hyperledger/fabric-protos-go/peer._Endorser_ProcessProposal_Handler
	/go/src/github.com/hyperledger/fabric/vendor/github.com/hyperledger/fabric-protos-go/peer/peer.pb.go:109
google.golang.org/grpc.(*Server).processUnaryRPC
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:1180
google.golang.org/grpc.(*Server).handleStream
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:1503
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:843
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371 channel=mychannel txID=0bafb81e
[33m2022-07-27 12:11:56.776 UTC 02fd WARN[0m [endorser] [33;1mProcessProposal[0m -> Failed to invoke chaincode channel=mychannel chaincode=titledeed error="error in simulation: failed to execute transaction 0bafb81e0b026767513a885afc3d87c57925df013c7532bbacdb75c056fbd1e2: could not launch chaincode titledeed:a65c28bd17770151d83e51e974b553907ffb11a9696fd7269aa8759b162a4707: timeout expired while starting chaincode titledeed:a65c28bd17770151d83e51e974b553907ffb11a9696fd7269aa8759b162a4707 for transaction"
[34m2022-07-27 12:11:56.776 UTC 02fe INFO[0m [comm.grpc.server] [34;1m1[0m -> unary call completed grpc.service=protos.Endorser grpc.method=ProcessProposal grpc.request_deadline=2022-07-27T12:09:56.774Z grpc.peer_address=10.244.0.1:7094 grpc.code=OK grpc.call_duration=5m0.002310146s

Chaincode pod logs----

Dockerfile
Dockerfile_old
META-INF
README.md
build.sh
ci
code.tar.gz
connection.json
dist
docker
entrypoint.sh
keystore
metadata.json
metadata.json_old
node_modules
package-lock.json
package.json
run_deploy.sh
src
tests
titledeed.tgz
transaction_data
tsconfig.json
tslint.json

> blk-chn-chaincode@0.0.1 start /go/src/github.com/hyperledger/chaincode
> fabric-chaincode-node server --chaincode-address 0.0.0.0:9999 --chaincode-id titledeed

2022-07-27T08:48:20.023Z [32minfo[39m [c-api:./lib/annotations/object.js]                 @Object args: Target -> %s "Function" 
2022-07-27T08:48:20.026Z [32minfo[39m [c-api:./lib/annotations/transaction.js]            @Returns args: ", Property Key -> titledeedExists, Return Type -> boolean,","Target ->","TitledeedContract" 
2022-07-27T08:48:20.027Z [32minfo[39m [c-api:./lib/annotations/transaction.js]            @Transaction args: "Property Key -> titledeedExists, Commit -> false,","Target ->","TitledeedContract" 
2022-07-27T08:48:20.028Z [32minfo[39m [c-api:./lib/annotations/transaction.js]            @Transaction args: "Property Key -> createTitledeed, Commit -> true,","Target ->","TitledeedContract" 
2022-07-27T08:48:20.029Z [32minfo[39m [c-api:./lib/annotations/transaction.js]            @Returns args: ", Property Key -> readTitledeed, Return Type -> Titledeed,","Target ->","TitledeedContract" 
2022-07-27T08:48:20.030Z [32minfo[39m [c-api:./lib/annotations/transaction.js]            @Transaction args: "Property Key -> readTitledeed, Commit -> false,","Target ->","TitledeedContract" 
2022-07-27T08:48:20.031Z [32minfo[39m [c-api:./lib/annotations/transaction.js]            @Transaction args: "Property Key -> updateTitledeed, Commit -> true,","Target ->","TitledeedContract" 
2022-07-27T08:48:20.031Z [32minfo[39m [c-api:./lib/annotations/transaction.js]            @Transaction args: "Property Key -> deleteTitledeed, Commit -> true,","Target ->","TitledeedContract" 
2022-07-27T08:48:20.032Z [32minfo[39m [c-api:./lib/annotations/info.js]                   @Info args: "Info -> [object Object],","Target ->","TitledeedContract" 
2022-07-27T08:48:20.063Z [32minfo[39m [c-api:contracts-spi/bootstrap.js]                  No metadata file supplied in contract, introspection will generate all the data

**Comment by dviejokfs** [comment]
Hi @anzalbeg 

Try to don't specify the chaincode address and chaincode id, this is already specified by the env variables injected by the `hlf-operator`

```bash
CHAINCODE_ID=chaincode:xxxxx
CHAINCODE_SERVER_ADDRESS=0.0.0.0:7052
CHAINCODE_TLS_DISABLED=true
CORE_CHAINCODE_ADDRESS=0.0.0.0:7052
CORE_CHAINCODE_ID=chaincode:xxxxx
CORE_PEER_TLS_ENABLED=false
```

Then you should be able to launch the chaincode in Kubernetes cluster using this command as the cmd in Dockerfile:

```bash
fabric-chaincode-node server
```

**Comment by anzalbeg** [comment]
Hi @dviejokfs ,

When not passing the chaincode address and chaincode id, i am getting the error "Missing required arguments: chaincode-address, chaincode-id,"

**Comment by anzalbeg** [comment]
Thanks its working now

**Comment by anzalbeg** [comment]
Thanks for the suggestions it is working as expected
