### ISSUE TITLE
adding new Orgs

### ISSUE THREAD

**Issue by Sushain96** [kfsoftware/hlf-operator#104]
Can this setup be used to add Orgs and CAs to an existing network??

**Comment by dviejokfs** [comment]
@Sushain96 
Yes, you can deploy a new peer organization with the hlf-operator and join the peers to an existing network

**Comment by adityajoshi12** [comment]
@Sushain96 you can get an idea from here https://youtu.be/0VUx9CYn4z8

**Comment by dviejokfs** [comment]
Hello @Sushain96 

Channel management has been redesigned in v1.8.0; take a look at the [Getting Started](https://labs.hyperledger.org/hlf-operator/docs/channel-management/getting-started/) to create the channel and [this documentation to add organizations](https://labs.hyperledger.org/hlf-operator/docs/channel-management/manage)

**Comment by thapld** [comment]
Hi, @dviejokfs Please update document step by step to add new cluster org to exist network
