### ISSUE TITLE
Delay with CA Istio 

### ISSUE THREAD

**Issue by rijoblockchain** [kfsoftware/hlf-operator#109]
In an EKS cluster with private node group setup, registering entities in CA with istio gateway causing delay (almost 5 mins to register one peer).

However, registering with CA without istio setup and opening all TCP in the cluster node gives immediate response. Works fine.

Appreciate any help. Thank you.

**Comment by dviejokfs** [comment]
Hi @rijoblockchain 

Can you give more insights about your environment? Are other services inside your cluster working correctly?

**Comment by dviejokfs** [comment]
@rijoblockchain 

I'm closing the issue, please; if the issue remains active open another issue or join the discord.
