### ISSUE TITLE
unable to create ca

### ISSUE THREAD

**Issue by ramesh-m99** [kfsoftware/hlf-operator#112]
**kubectl hlf ca create --storage-class=do-block-storage --capacity=2Gi --name=org1-ca --enroll-id=enroll --enroll-pw=enrollpw --namespace=fabric**

error :
Error: the server could not find the requested resource (post fabriccas.hlf.kungfusoftware.es)

**Comment by dviejokfs** [comment]
Hello @ramdisk-ott 

You need to install the helm chart before proceeding with creating the CA

**Comment by ramesh-m99** [comment]
thanks, @dviejokfs.
