### ISSUE TITLE
Parameterize channels in network config

### ISSUE THREAD

**Issue by ZappaBoy** [kfsoftware/hlf-operator#114]
*Regarding #113*

Creating a server to expose REST API I got this error:
```shell
Error: Failed to create Channel. channel name should match Regex /^[a-z][a-z0-9.-]*$/, but got _default
```
It seems that the underscore in `_default` is an unsupported symbol, so I solved renaming the default channel in `default` in all the project.

Also as noticed by @dviejokfs https://github.com/hyperledger-labs/hlf-operator/pull/113#issuecomment-1231823243:
*We should parameterized the channels in the resultant network config*.
*The `_default` channel is useful for GoLang applications, but for Node.JS applications it fails.*

**Comment by dviejokfs** [comment]
@ZappaBoy  This is available using the `--channels` flag in the `inspect` command in v1.8.0
