### ISSUE TITLE
resources updation in CRD doesn't update kubernetes object.

### ISSUE THREAD

**Issue by adityajoshi12** [kfsoftware/hlf-operator#118]
Updating the CRD with parameters such as CPU and Memory for `peers`, `couchdb` and `chaincode` doesn't update the underneath resource.

Expected output: 
Updating the memory and CPU parameters in the CRD should update the resources in pods/deployments

**Comment by dviejokfs** [comment]
Can you describe the steps to reproduce it? @adityajoshi12 

I tested it locally and remotely, and it works for me in KinD, AKS and EKS.

**Comment by adityajoshi12** [comment]
I identified the root cause of this issue, my CRDs were in a failed state and that was the reason that operator was not able to update the resources in the pod.

Closing this issue.
