### ISSUE TITLE
chaincode install

### ISSUE THREAD

**Issue by JohanIskandar** [kfsoftware/hlf-operator#126]
Hello,

   I am running KinD on Mac Intel Processor and while following https://github.com/hyperledger-labs/hlf-operator, when at chaincode install part, I got the following error message. What would be the possible causes and how to fix it. Thank you

```
kubectl hlf chaincode install --path=./chaincode.tgz \
    --config=org1.yaml --language=golang --label=$CHAINCODE_LABEL --user=admin --peer=org1-peer1.default

Error: unable to verify if cc is installed on grpcs://peer1-org1.localho.st:443. Got error: Transaction processing for endorser [peer1-org1.localho.st:443]: Endorser Client Status Code: (2) CONNECTION_FAILED. Description: dialing connection on target [peer1-org1.localho.st:443]: waiting for connection failed: context deadline exceeded
```

regards,

Johan

**Comment by dviejokfs** [comment]
@JohanIskandar 

This is a deployment problem, please check that you have connectivity to the peers and the cluster

**Comment by JohanIskandar** [comment]
> @JohanIskandar
> 
> This is a deployment problem, please check that you have connectivity to the peers and the cluster

thank you
