### ISSUE TITLE
ConfigMap of peer restore sometimes somehow

### ISSUE THREAD

**Issue by luca-simonetti** [kfsoftware/hlf-operator#130]
we changed some value in the configmap org1-peer0--peer--core, which is basically the core.yaml of the peer, but somehow the changes are reverted to original after some time. We don't really know when.

How can they stay permanently?

**Comment by dviejokfs** [comment]
Hi @luca-simonetti 

The configmap of the peer is automatically generated by the operator, that's why it will get restored when operator synchronizes the peer.

What kind of configuration you want to customize?

**Comment by luca-simonetti** [comment]
hi!
the configuration we're trying to change are basically three and they all reside in core.yaml

```
totalQueryLimit
limits. endorserService
limits. deliverService
```

**Comment by dviejokfs** [comment]
@luca-simonetti 

You can use environment variables to configure these properties dynamically.

You can look at this: https://stackoverflow.com/a/48868576/5468614
