### ISSUE TITLE
Error joining an orderer or creating the main channel manifest

### ISSUE THREAD

**Issue by cw6365** [kfsoftware/hlf-operator#132]
I'm getting the following errors on GKE when joining the orderer

Any ideas.. i'm a bit stumped, from what ive read the nil pointer is something to do with not finding the endpoint? but all looks ok and i can ping the endpoint. Any help would be great, thanks.

**Comment by dviejokfs** [comment]
Hi @cw6365 

Can you share the orderer CRD?

```
 kubectl get fabricorderernodes <fabric_ord_name> -n <ns> -o yaml   
```

Not sure if your set up is with Istio or using the kubernetes IP.

**Comment by cw6365** [comment]
@dviejokfs thanks for getting back. We're using Istio, ive listed the orderer yaml below. Once i've got a fix i'll change the certs.

I have tried both values of ecm-orderer1 and the full domain in the main channel manifest with no luck. Thanks.

**Comment by dviejokfs** [comment]
Hi @cw6365, you are missing the hosts in the `adminIstio` property, that's the main reason.

**Comment by meetpandya27** [comment]
How can I update adminIstio property ?
