### ISSUE TITLE
Failed to connect to chaincode

### ISSUE THREAD

**Issue by cw6365** [kfsoftware/hlf-operator#139]
When i query the chaincode i get the error that the chaincode couldnt be launched. It doesnt even look like its connecting to the correct internal service  IP. Any ideas? thanks.

**Comment by cw6365** [comment]
This setup is on GKE. Look something to do with the grpc connection using the connection.json. Is there anything i need to add to this file to get it working?

**Comment by dviejokfs** [comment]
are the chaincodes and the peers in the same namespace? @cw6365

**Comment by cw6365** [comment]
@dviejokfs that was the issue thanks
