### ISSUE TITLE
In kubectl hlf  externalChainCode provide argument for selecting imagePullPolicy

### ISSUE THREAD

**Issue by JibinNajeeb** [kfsoftware/hlf-operator#142]
### What would you like to be added?

In kubectl hlf  externalChainCOde plugin the ImagePullPolicy is set as always. In my machine I don't have external access to repository.
It will be helpful if in imagePullPolicy different options are provided
```
func (c *createExternalChaincodeCmd) run() error {
	fabricChaincodeSpec := v1alpha1.FabricChaincodeSpec{
		Image:            c.image,
		ImagePullPolicy:  corev1.PullAlways, //I think this is the reason
		PackageID:        c.packageID,
		ImagePullSecrets: []corev1.LocalObjectReference{},
		Credentials:      nil,
		Replicas:         c.replicas,
	}
}
```

### Why is this needed?

In kubectl hlf  externalChainCOde plugin the ImagePullPolicy is set as always. In my machine I don't have direct external access to any public repository.

**Comment by dviejokfs** [comment]
Will be implemented in 1.9.0

**Comment by JibinNajeeb** [comment]
Also consider for 
peer create and ordnode create, Thanks

kubectl hlf peer create --image=$PEER_IMAGE --version=$PEER_VERSION --storage-class=standard --enroll-id=org1-peer1 --mspid=Org1MSP --enroll-pw=peerpw --capacity=5Gi --name=org1-peer1 --ca-name=org1-ca.fabric --namespace=fabric --statedb=couchdb --k8s-builder=true

kubectl hlf ordnode create  --storage-class=standard --image=$ORDERER_IMAGE --version=$ORDERER_VERSION --enroll-id=orderer --mspid=OrdererMSP --enroll-pw=ordererpw --capacity=2Gi --name=ord-node1 --ca-name=ord-ca.fabric --namespace=fabric

**Comment by JibinNajeeb** [comment]
Also consider for 
peer create and ordnode create, Thanks

kubectl hlf peer create --image=$PEER_IMAGE --version=$PEER_VERSION --storage-class=standard --enroll-id=org1-peer1 --mspid=Org1MSP --enroll-pw=peerpw --capacity=5Gi --name=org1-peer1 --ca-name=org1-ca.fabric --namespace=fabric --statedb=couchdb --k8s-builder=true

kubectl hlf ordnode create  --storage-class=standard --image=$ORDERER_IMAGE --version=$ORDERER_VERSION --enroll-id=orderer --mspid=OrdererMSP --enroll-pw=ordererpw --capacity=2Gi --name=ord-node1 --ca-name=ord-ca.fabric --namespace=fabric

**Comment by JibinNajeeb** [comment]
Also consider for 
peer create and ordnode create, Thanks

kubectl hlf peer create --image=$PEER_IMAGE --version=$PEER_VERSION --storage-class=standard --enroll-id=org1-peer1 --mspid=Org1MSP --enroll-pw=peerpw --capacity=5Gi --name=org1-peer1 --ca-name=org1-ca.fabric --namespace=fabric --statedb=couchdb --k8s-builder=true

kubectl hlf ordnode create  --storage-class=standard --image=$ORDERER_IMAGE --version=$ORDERER_VERSION --enroll-id=orderer --mspid=OrdererMSP --enroll-pw=ordererpw --capacity=2Gi --name=ord-node1 --ca-name=ord-ca.fabric --namespace=fabric

**Comment by JibinNajeeb** [comment]
Also consider for 
peer create and ordnode create, Thanks

kubectl hlf peer create --image=$PEER_IMAGE --version=$PEER_VERSION --storage-class=standard --enroll-id=org1-peer1 --mspid=Org1MSP --enroll-pw=peerpw --capacity=5Gi --name=org1-peer1 --ca-name=org1-ca.fabric --namespace=fabric --statedb=couchdb --k8s-builder=true

kubectl hlf ordnode create  --storage-class=standard --image=$ORDERER_IMAGE --version=$ORDERER_VERSION --enroll-id=orderer --mspid=OrdererMSP --enroll-pw=ordererpw --capacity=2Gi --name=ord-node1 --ca-name=ord-ca.fabric --namespace=fabric
