### ISSUE TITLE
Unable to update to version 1.8.4

### ISSUE THREAD

**Issue by LeonColt** [kfsoftware/hlf-operator#143]
### What happened?

I am trying to install version 1.8.4, but it is not found

### What did you expect to happen?

Should be able to install version 1.8.4

### How can we reproduce it (as minimally and precisely as possible)?

helm install hlf-operator --version=1.8.4 kfs/hlf-operator
will produce
Error: INSTALLATION FAILED: chart "hlf-operator" matching 1.8.4 not found in kfs index. (try 'helm repo update'): no chart version found for hlf-operator-1.8.4

**Comment by demshin** [comment]
It's working for me.
Can you show `helm search repo hlf-operator --versions`?

**Comment by dviejokfs** [comment]
I published missing helm versions for 1.8.3 and 1.8.4

Should work now
