### ISSUE TITLE
Generate network config failed

### ISSUE THREAD

**Issue by snakelu** [kfsoftware/hlf-operator#149]
### What would you like to be added?
I use hlf sdk to generate network config, But I reported an error when exporting network config.
> https://github.com/hyperledger/bevel-operator-fabric/blob/main/kubectl-hlf/cmd/networkconfig/create.go

error message: template: networkConfig:23:15: executing "networkConfig" at <$org.OrderingServices>: can't evaluate field OrderingServices in type *helpers.Organization
status: failed

### Why is this needed?

![image](https://user-images.githubusercontent.com/9976408/222318656-d800b767-02d0-4d11-acf2-93d2f9106da2.png)

**Comment by yuecelm** [comment]
I have the same issue, how you solved it?
