### ISSUE TITLE
Explain the different between chart and charts folder

### ISSUE THREAD

**Issue by sownak** [kfsoftware/hlf-operator#152]
### What would you like to be added?

It will be good to add README.md in `charts` and `chart` folder. If one of them is not needed or they are duplicate, then they should be merged.

### Why is this needed?

So that developers and users are able to understand about this repository and the code better.

**Comment by adityajoshi12** [comment]
`chart` folder has the operator helm chart while the `charts` folder has the helm charts for the Peer, Orderer and CAs

**Comment by sownak** [comment]
@adityajoshi12 Can this be merged or Bevel charts used for Peer, Orderer and CAs is some way?
