### ISSUE TITLE
Publish the helmcharts on hyperledger.github.io/bevel-operator-fabric/

### ISSUE THREAD

**Issue by sownak** [kfsoftware/hlf-operator#154]
### What would you like to be added?

The helm charts are to be published via hyperledger.github.io

### Why is this needed?

So that they are easily discoverable and all time available.

**Comment by dviejokfs** [comment]
@sownak 
Can you advise on the repository to be used?

**Comment by sownak** [comment]
@dviejokfs Same as hyperledger, please check bevel release workflows. We have done the chart releases via Github Actions
