### ISSUE TITLE
Documentation for operatorUI and operatorAPI

### ISSUE THREAD

**Issue by vipulsha22** [kfsoftware/hlf-operator#159]
Hi , 

Where can I find usage documentation for operatorUI and operatorAPI. This is my first attempt to use operator.

Regards,

**Comment by dviejokfs** [comment]
@vipulsha22 
https://hyperledger.github.io/bevel-operator-fabric/docs/operator-ui/getting-started

**Comment by vipulsha22** [comment]
Thank you. It's coming for me now. Got confused with port.
