### ISSUE TITLE
Issue while joining orderer node to a channel while using istio: connection timed out

### ISSUE THREAD

**Issue by pshgpt** [kfsoftware/hlf-operator#168]
### What happened?

Running this command :
kubectl hlf ordnode join --block=mychannel.block --name=orderer-node1 --identity=admin-tls-ordservice.yaml --namespace=default

Error: Post "https://143.244.138.201:0/participation/v1/channels": dial tcp 143.244.138.201:0: connect: connection timed out

### What did you expect to happen?

Status code=201

### How can we reproduce it (as minimally and precisely as possible)?

kubectl hlf ordnode join --block=mychannel.block --name=orderer-node1 --identity=admin-tls-ordservice.yaml --namespace=default

### Kubernetes version

pool-mxjx1jwnv-fa6xb   Ready    <none>   60m   v1.27.2   10.122.0.3    143.244.138.201   Debian GNU/Linux 11 (bullseye)   6.1.0-0.deb11.6-amd64   containerd://1.6.20
pool-mxjx1jwnv-fa6xr   Ready    <none>   60m   v1.27.2   10.122.0.2    143.244.138.114   Debian GNU/Linux 11 (bullseye)   6.1.0-0.deb11.6-amd64   containerd://1.6.20

**Comment by dviejokfs** [comment]
Are you using Istio?

**Comment by pshgpt** [comment]
@dviejokfs yes I'm

**Comment by pshgpt** [comment]
Can someone help on this issue?

**Comment by adityajoshi12** [comment]
Please check the Orderer CRD, it doesn't has the port configured correctly.
