### ISSUE TITLE
Support for legacy channel management API in hlf plugin

### ISSUE THREAD

**Issue by adityajoshi12** [kfsoftware/hlf-operator#171]
### What would you like to be added?

Older version of the hlf plugin had channel management APIs like channel join and anchor peer updates. This comes handy if someone doesn't want to use the CRDs for channel management.

### Why is this needed?

Channel management via CRDs is not useful in all the secenrio, we can support both the approaches for channel management.

**Comment by dviejokfs** [comment]
Hi @adityajoshi12 

Do you refer to the documentation? or the hlf plugin commands?

If you refer to the documentation, we could recover the previous documentation.

About the hlf plugin commands, I don't think they were removed, but let me check.

**Comment by adityajoshi12** [comment]
Channel operation are removed in the recent version from the HLF plugin. I checked the hlf plugin implementation.

**Comment by dviejokfs** [comment]
@adityajoshi12 
I think the workaround, except if there's any improvement over that, it's to recommend using a previous version of kubectl plugin.

Dependencies have been modified in 1.9.0 to not use internal packages anymore, since it was very difficult to maintain compatibility.

**Comment by adityajoshi12** [comment]
@dviejokfs 
Let me check if we can use external dependencies, else we can use the older version
