### ISSUE TITLE
Error while registering peer 

### ISSUE THREAD

**Issue by pshgpt** [kfsoftware/hlf-operator#176]
### What happened?

I'm getting this error while registering the peer identity. Do you have any idea for it ?
{"hosts":null,"certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\nMIIBGTCBwQIBADARMQ8wDQYDVQQDEwZlbnJvbGwwWTATBgcqhkjOPQIBBggqhkjO\nPQMBBwNCAAS7ZfLWMaAv8a8RAeplxMaKq3C742dH31C6ukoQTCVcnaEjWvC4rkmK\n5AcyRFNAIGn1LNokMwBjqEdFepmFrllloE4wTAYJKoZIhvcNAQkOMT8wPTA7BgNV\nHREENDAygjBpcC0xOTItMTY4LTI1LTQwLmFwLXNvdXRoZWFzdC0xLmNvbXB1dGUu\naW50ZXJuYWwwCgYIKoZIzj0EAwIDRwAwRAIgVovR5Oh3ENujdBAH4BPLpDMppNsN\nIIo1mYv1BERjwdsCIH4NF2o8CSiGt4KwaOfzYdBpVf6ijd2gTvXISNJnj148\n-----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","NotBefore":"0001-01-01T00:00:00Z","NotAfter":"0001-01-01T00:00:00Z","ReturnPrecert":false,"CAName":""}: Post "https://143.244.138.201:30112/enroll": x509: certificate is valid for [127.0.0.1](http://127.0.0.1/), not [143.244.138.201](http://143.244.138.201/)

### What did you expect to happen?

Created successfully

### How can we reproduce it (as minimally and precisely as possible)?

kubectl hlf ca register --name=ca-test --user=peer0-test --secret=peerpw --type=peer --enroll-id enroll --enroll-secret=enrollpw --mspid testOrgMSP 

### Kubernetes version

<details>

  ```console
  # kubectl get nodes -o wide
  ```

</details>

**Comment by adityajoshi12** [comment]
While setting up the CA ensure that you have added the all the hosts and the FQDN in the CSR section.  You can use `--output` flag to view your CA CustomResource (CR)

**Comment by thapld** [comment]
I play with same error. Please guide in your course video

**Comment by thapld** [comment]
I have to install istio and add domain first.
