### ISSUE TITLE
There are files with incompatible licenses that must be removed.

### ISSUE THREAD

**Issue by ryjones** [kfsoftware/hlf-operator#184]
### What happened?

[Please review and remove these files](https://lfscanning.org/reports/hyperledger/bevel-2023-07-14-2ecaf575-50b9-4ffc-ad86-103978b6792b.html)

### What did you expect to happen?

Files removed

### How can we reproduce it (as minimally and precisely as possible)?

Look at report

**Comment by dviejokfs** [comment]
What needs to be done exactly? @ryjones

**Comment by ryjones** [comment]
@dviejokfs the files with incompatible licenses must be removed
