### ISSUE TITLE
CA Service Port name conflict with Istio Ingress

### ISSUE THREAD

**Issue by shutupflanders** [kfsoftware/hlf-operator#200]
### What happened?

When running the command 
```
kubectl hlf ca create --storage-class=gp2 --capacity=2Gi --name=org1-ca  --enroll-id=enroll --enroll-pw=enrollpw --namespace=hyperledger --hosts org1-ca.hlf.<redacted>
```
I'm unable to contact the `/cainfo` endpoint of the generated deployment, it results in
```
curl -v -k -L https://org1-ca.hlf.<<redacted>>/cainfo
*   Trying <<redacted_public_ip>>...
* TCP_NODELAY set
* Connected to org1-ca.hlf.<<redacted>> (<<redacted_public_ip>>) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* stopped the pause stream!
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

This also prevents the `ca register` command from contacting the server.

### What did you expect to happen?

The `/cainfo` endpoint should return a valid response and allow the `ca register` command to register a user.

### How can we reproduce it (as minimally and precisely as possible)?

1. Install the operator on an EKS cluster with Istio and ingress-gateway configured via Helm
2. Register a CA (ensuring DNS is properly set up)
3. Attempt to curl the newly created service or run the `ca register` command

### Anything else we need to know?

The Fix for the following is to modify the service port name to the proper protocol:

I.e: in services -> `org1-ca`
![image](https://github.com/hyperledger/bevel-operator-fabric/assets/3372012/a5e2c839-07ca-4ac1-a971-2f80ca624dee)
becomes
![image](https://github.com/hyperledger/bevel-operator-fabric/assets/3372012/41b75855-4c95-4272-86b4-da1137d85b39)

Once saved, the service is contactable and the above error is resolved.

### Kubernetes version

v1326.6-eks-a5565ad

**Comment by mrkaurelius** [comment]
Hi, there is any progress in this issue?
