### ISSUE TITLE
 Channel signupdate command fails

### ISSUE THREAD

**Issue by ankit-wasnik-pcn** [kfsoftware/hlf-operator#228]
### What happened?

"kubectl hlf channel signupdate" command is failing with error "Error: open : no such file or directory" even though I have the file with correct permissions.

**Command:**
`kubectl hlf channel signupdate --channel mychannel -f org3-ec-config-update-in-envelope.pb --config networkConfig.yaml --user=admin --mspid=Org1MSP`

![hlf-sign-update-issue](https://github.com/user-attachments/assets/0c1d0d55-8ede-489a-b1d5-63926962a71d)

### What did you expect to happen?

The command should not fail if config update file exists.

### How can we reproduce it (as minimally and precisely as possible)?

1. Setup minimal fabric network.
2. Create a channel
3. Update channel config.
4. Sign the updated channel config file.

### Anything else we need to know?

hlf-operator plugin version - 1.10.0

### Kubernetes version

<details>

  ```console
 v1.29.0-eks-5e0fdde
  ```

</details>

**Comment by adityajoshi12** [comment]
Please use the latest version of plugin, this has been fixed [here](https://github.com/hyperledger/bevel-operator-fabric/pull/216)

**Comment by ankit-wasnik-pcn** [comment]
It worked. Thanks @adityajoshi12
