### ISSUE TITLE
Issue while creating the Orderer node using the generated yaml from plugin,

### ISSUE THREAD

**Issue by junaid18183** [kfsoftware/hlf-operator#34]
I created a YAML for the ordnode as below, 

`kubectl hlf ordnode create --image=hyperledger/fabric-orderer--version=2.4.1 --namespace fabric --enroll-id=orderer --mspid=OrdererMSP --enroll-pw=ordererpw --capacity=2Gi --name=ord-node1 --ca-name=ord-ca.fabric  -o > ord-node1.yaml`

I am planning to use the fabric namespace so have added the --namespace field, Also my cluster has default storageclass so I have omitted the `--storage-class` flag. 

But when I apply the generated `ord-node1.yaml` its failing with below error.

`❯ kubectl apply -f ord-node1.yaml
error: error validating "ord-node1.yaml": error validating data: [ValidationError(FabricOrderingService.spec): unknown field "bootstrapMethod" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.spec, ValidationError(FabricOrderingService.spec): unknown field "channelParticipationEnabled" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.spec, ValidationError(FabricOrderingService.spec): unknown field "genesis" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.spec, ValidationError(FabricOrderingService.spec): unknown field "hostAliases" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.spec, ValidationError(FabricOrderingService.spec): unknown field "pullPolicy" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.spec, ValidationError(FabricOrderingService.spec): unknown field "replicas" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.spec, ValidationError(FabricOrderingService.spec): unknown field "resources" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.spec, ValidationError(FabricOrderingService.spec): unknown field "secret" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.spec, ValidationError(FabricOrderingService.spec): missing required field "enrollment" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.spec, ValidationError(FabricOrderingService.spec): missing required field "nodes" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.spec, ValidationError(FabricOrderingService.spec): missing required field "systemChannel" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.spec, ValidationError(FabricOrderingService.status): unknown field "adminPort" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.status, ValidationError(FabricOrderingService.status): unknown field "message" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.status, ValidationError(FabricOrderingService.status): unknown field "operationsPort" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.status, ValidationError(FabricOrderingService.status): unknown field "port" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.status, ValidationError(FabricOrderingService.status): unknown field "signCert" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.status, ValidationError(FabricOrderingService.status): unknown field "tlsAdminCert" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.status, ValidationError(FabricOrderingService.status): unknown field "tlsCert" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.status, ValidationError(FabricOrderingService.status): missing required field "conditions" in es.kungfusoftware.hlf.v1alpha1.FabricOrderingService.status]; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by dviejokfs** [comment]
Hi @junaid18183 

Can you try removing this part of the command?
`-o > ord-node1.yaml`

Also try to update the version of the kubectl plugin:
```bash
kubectl krew upgrade hlf
```

**Comment by junaid18183** [comment]
Thanks @dviejokfs  upgrading the hlf plugin solved the issue, marking it as closed
