### ISSUE TITLE
Can I use the peer image of the docker hub?

### ISSUE THREAD

**Issue by yby654** [kfsoftware/hlf-operator#36]
I want to use hyperledger/fabric-peer 2.2 or custom peer image.
Is it possible?
Please reply.

**Comment by dviejokfs** [comment]
You can use whatever docker image you wish.

The only thing you need to keep in mind is to make sure that building and launching the chaincode is supported by the image, either as [an external service](https://hyperledger-fabric.readthedocs.io/en/release-2.2/cc_service.html) or directly in Kubernetes(https://github.com/kfsoftware/externalbuilder or https://github.com/postfinance/hlfabric-k8scc)

**Comment by yby654** [comment]
참고하여 테스트 해보겠습니다.
답변해주셔서 감사합니다.

**Comment by yby654** [comment]
I'll refer to it and test it.
Thank you for your answer.
