### ISSUE TITLE
Verify that osnadmin client allow you to have any orderer node join/unjoin any channel

### ISSUE THREAD

**Issue by nkaramolegos** [kfsoftware/hlf-operator#50]
Hello, in case the number of channel is increased I [see](https://hyperledger-fabric.readthedocs.io/en/latest/create_channel/create_channel_participation.html) that from v2.3+ I can increase the orderer nodes and use them in the new channels. Is this supported by the operator?

**Comment by dviejokfs** [comment]
This is how the network works in the getting started, using the channel participation API.
When creating a channel:
https://kfsoftware.github.io/hlf-operator/docs/getting-started#create-a-channel

This step is used to join the orderer to the channel:
```bash
kubectl hlf ordnode join --block=demo.block --name=ordservice --namespace=default --identity=admin-tls-ordservice.yaml
```

**Comment by nkaramolegos** [comment]
Perfect, so in case I need to generate a new channel (to join my already available orgs) I can create a new orderer node and join it to the new channel. In this way I can balance the load to the different ordering nodes. Correct?

**Comment by dviejokfs** [comment]
Yes, with a small catch, if you want to add the orderer to the consensus, you'll need to add the orderer to the consenters field in the channel.

You can find some leads here: https://github.com/kfsoftware/meetup-k8s-hlf#add-them-as-consenters

**Comment by nkaramolegos** [comment]
Hello, After, deploying my one channel network with one orderer node (i.e `ordnode-1`) I am using
```

export ORG_ORD_ORD1_USER=ord1_orgOrd_id
export ORG_ORD_ORD1_PASS=ord1_orgOrd_pass

kubectl hlf ca register --name=ordererorg-ca --user=$ORG_ORD_ORD1_USER --secret=$ORG_ORD_ORD1_PASS --type=orderer --enroll-id=$ORG_ORD_CA_BOOTSTRAP_IDENTITY --enroll-secret=$ORG_ORD_CA_BOOTSTRAP_PASS --mspid=OrdererMSP
kubectl hlf ordnode create --image=$ORDERER_IMAGE --version=$ORDERER_VERSION  --storage-class=standard --enroll-id=$ORG_ORD_ORD1_USER --mspid=OrdererMSP --enroll-pw=$ORG_ORD_ORD1_PASS --capacity=2Gi --name=ordnode-2 --ca-name=ordererorg-ca.default --output > resources/orderer/orderer2.yaml
kubectl apply -f ./resources/orderer/orderer2.yaml
kubectl wait --timeout=180s --for=condition=Running fabricorderernodes.hlf.kungfusoftware.es --all
kubectl hlf ordnode join --block=ch1.block --name=ordnode-2 --namespace=default --identity=admin-tls-ordservice.yaml
sleep 10
kubectl hlf inspect --output ordservice.yaml -o OrdererMSP -o Org1MSP -o Org2MSP -o Org3MSP
kubectl hlf utils adduser --userPath=admin-ordservice.yaml --config=ordservice.yaml --username=$ORG_ORD_ADMIN_USER --mspid=OrdererMSP
sleep 30
kubectl hlf channel consenter add --config=ordservice.yaml --orderers=ordnode-2.default --user=$ORG_ORD_ADMIN_USER --channel=ch1 --mspid=OrdererMSP --output=add_orderers_consenter.pb
sleep 30
kubectl hlf channel update --channel=ch1 -f add_orderers_consenter.pb --config=ordservice.yaml --user=$ORG_ORD_ADMIN_USER --mspid=OrdererMSP
```
To deploy a new orderer node and add him as consenter. After that I am trying to invoke the 
`kubectl hlf chaincode invoke --config=org1.yaml --user=$ORG1_ADMIN_USER --peer=org1-peer0.default --chaincode=fabcar --channel=ch1 --fcn=initLedger -a '[]'
`
which works perfect. So for testing I delete my `kind` cluster and I create a new one where I deploy again the same network with the second orderer too. After everything is ok I delete the deployment of the first orderer node (ie `ordnode-1`) in order to simulate the case where this node is dead `(kubectl delete -n default deployment ordnode-2)` and I am expecting the `ordnode-2` to be used, however I am getting the following error

`Error: CreateAndSendTransaction failed: SendTransaction failed: calling orderer '172.18.0.2:32729' failed: Orderer Server Status Code: (503) SERVICE_UNAVAILABLE. Description: no Raft leader
`

 when I run 
`kubectl hlf chaincode invoke --config=org1.yaml --user=$ORG1_ADMIN_USER --peer=org1-peer0.default --chaincode=fabcar --channel=ch1 --fcn=initLedger -a '[]'
`
I believe that in someway I have to inform the `org1.yaml` file to be informed for the second orderer node.

Also, when my network relies to  majority consensus?

**Comment by nkaramolegos** [comment]
Edit: I found that I have to call:
```
kubectl hlf inspect --output org1_new.yaml -o Org1MSP -o Org2MSP -o Org3MSP -o OrdererMSP
kubectl hlf utils adduser --userPath=admin-org1.yaml --config=org1_new.yaml --username=$ORG1_ADMIN_USER --mspid=Org1MSP
```

to update the org1.yaml (i.e org1_new.yaml) and then to use this new yaml to invoke the init ledger transaction (after deleting ordnode-1), again the error remains.  Also, In case I have 3 orderer nodes how to set the  majority consensus (i.e one can be dead)

**Comment by nkaramolegos** [comment]
Hmm. Maybe this behavior is due to Raft characteristics. Specifically, 3 orderers can reach consensus even if one does not agree. But, that does not allow for continued operation if one of those nodes is interrupted and is not responding.

**Comment by dviejokfs** [comment]
Closing the issue as it seems there's a solution
