### ISSUE TITLE
Timeout while registering user for the peers

### ISSUE THREAD

**Issue by kapilvk** [kfsoftware/hlf-operator#57]
When I use the command `kubectl hlf ca register --name=org1-ca --user=org1-peer1 --secret=peerpw --type=peer --enroll-id enroll --enroll-secret=enrollpw --mspid=Org1MSP --namespace=fabric` , I face a timeout issue. 

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/94164078/157240477-465ff4b1-f3b6-436b-b190-bb52a5613bb2.png">

**Comment by dviejokfs** [comment]
Hi @kapilvk 

Where is the network being deployed?  It seems you're trying to access directly the Kubernetes node and this Kubernetes node is not accessible from your machine.

If this is the case, you should use Istio to expose the components deployed in the cluster through a common IP Address, take a look at this documentation:
[https://kfsoftware.github.io/hlf-operator/docs/operator-guide/istio](https://kfsoftware.github.io/hlf-operator/docs/operator-guide/istio)

**Comment by hyoinandout** [comment]
@dviejokfs 

I have same issue in local k8s cluster(kind, refer : https://github.com/kfsoftware/meetup-k8s-hlf)
Would you please describe more about above doc https://kfsoftware.github.io/hlf-operator/docs/operator-guide/istio?
I have a problem in  **_setting local DNS_**.

I configured /etc/hosts like (echo $PUBLIC_IP -> 543.32.1.0):
543.32.1.0 peer0.org1.example.com
543.32.1.0 ord1.ord.org.example.com

After that, I tried to register user for the peers, but the above issue problem occured again.

**Comment by paul-snively** [comment]
For what it's worth, I'm also experiencing this, with kind, following the "Getting Started" instructions verbatim.

**Comment by paul-snively** [comment]
Is there any news on this? It's literally a showstopping bug that appears when following the "Getting Started" instructions in the README by copying-and-pasting, which is not encouraging.

**Comment by dviejokfs** [comment]
Hi @paul-snively 

Getting started docs on the website were not up to date with the README instructions.

I have synchronized them in the PR #81 , can you try following the README instructions in the meantime?
