### ISSUE TITLE
Delete an orderer node or/and an organization from the channel

### ISSUE THREAD

**Issue by nkaramolegos** [kfsoftware/hlf-operator#58]
As I know in HLF I can not delete a channel. Thus, I am thinking as workaround to remove all the Orgs from the undesired (now) channel. Also, it will be needed to unjoin the orderer nodes. How can I do these using the hlf plugin? I have seen [[1]](https://github.com/kfsoftware/hlf-operator/blob/c4b95e2a36693e44145d22d4fe97bc94dc558056/kubectl-hlf/cmd/ordnode/removechannel.go), [[2]](https://github.com/kfsoftware/hlf-operator/blob/f3031be61c6b0a14265251c48bc5a8eddf8596d3/kubectl-hlf/cmd/channel/ordorg/remove.go) but I can not understand which is more appropriate

**Comment by dviejokfs** [comment]
The first one is to remove the channel from the orderer node.

The second one is to remove an organization from a channel.

If you want to unjoin orderer nodes, you need to use the first one: https://github.com/kfsoftware/hlf-operator/blob/main/kubectl-hlf/cmd/ordnode/removechannel.go

**Comment by dviejokfs** [comment]
Closing the issue since I believe the question is answered.
