### ISSUE TITLE
How the admin of CAs are created in the README example?

### ISSUE THREAD

**Issue by nkaramolegos** [kfsoftware/hlf-operator#59]
Hello, I can not understand how the admins of the CAs are created in order to be used for registering identities (e.g for the org's peers or users) as admin. Also, although I can see a `kubectl hlf ca register` command for --type=peer, I can not see any enroll command. Is this taking place during` kubectl hlf peer create` ?

**Comment by dviejokfs** [comment]
The operator enrolls the user before creating the Deployment in Kubernetes, you can see where this is being performed for TLS certificates.

https://github.com/kfsoftware/hlf-operator/blob/main/controllers/peer/peer_controller.go#L741-L758

**Comment by nkaramolegos** [comment]
Thank you again. I am closing the issue.
