### ISSUE TITLE
Wrong peer image version in yaml when using --output

### ISSUE THREAD

**Issue by nkaramolegos** [kfsoftware/hlf-operator#60]
I am trying to run: `kubectl hlf peer create --image=$PEER_IMAGE --version=$PEER_VERSION --storage-class=standard --enroll-id=peer0 --mspid=Org1MSP --enroll-pw=peerpw0 --capacity=5Gi --name=org1-peer0 --ca-name=org1-ca.default --output > resources/org1/peer0.yaml
`

and then `kubectl apply -f ./resources/org1/peer0.yaml`

but I am getting the error
`error: error validating "./resources/org1/peer0.yaml": error validating data: [ValidationError(FabricPeer.spec.couchdb): unknown field "image" in es.kungfusoftware.hlf.v1alpha1.FabricPeer.spec.couchdb, ValidationError(FabricPeer.spec.couchdb): unknown field "pullPolicy" in es.kungfusoftware.hlf.v1alpha1.FabricPeer.spec.couchdb, ValidationError(FabricPeer.spec.couchdb): unknown field "tag" in es.kungfusoftware.hlf.v1alpha1.FabricPeer.spec.couchdb]; if you choose to ignore these errors, turn validation off with --validate=false`

I am using the latest version of hlf-operator

**Comment by dviejokfs** [comment]
Can you upgrade your version of HLF-operator? It seems that the plugin is in a higher version that the operator running in the cluster.

Configuration of the CouchDB images was made available in 1.5.0.

You can use the hosted helm chart in https://github.com/kfsoftware/hlf-helm-charts

```bash
helm repo add kfs https://kfsoftware.github.io/hlf-helm-charts --force-update 
helm upgrade hlf-operator --version=1.5.0 kfs/hlf-operator
```

**Comment by nkaramolegos** [comment]
Thanks, I will try it. But in case I am in the latest commit of main branch the command `helm install hlf-operator ./chart/hlf-operator` does not install the latest version of operator?

**Comment by dviejokfs** [comment]
Seems this is resolved as I can see you've created a network in the recent issues.
I'm closing the issue, open a new issue if necessary @nkaramolegos
