### ISSUE TITLE
Question for more than one organization with two peers 

### ISSUE THREAD

**Issue by nkaramolegos** [kfsoftware/hlf-operator#61]
Hello, I am studying the _meetup-k8s-hlf_ repository and I have some questions

1) Can you please explain to me what [this](https://github.com/kfsoftware/hlf-operator#preparing-a-connection-string-for-the-peer) step is about? (same the first 4 commands [here](https://github.com/kfsoftware/meetup-k8s-hlf#join-peer-to-channel)). Also, should I make any change in case there is a second peer to the org? (e.g repeat this step for the second peer)
2) In [this](https://github.com/kfsoftware/meetup-k8s-hlf#approve--commit-chaincode-again) point where the peer of the second organization is joined to the channel  why the _Test chaincode_ and _Query all cars_ use the `org1-peer0.default` and not the peer of org2? Also, why the ledger is initialized again (it was already initialized by org1 in previous steps so after joining the channel should copy the ledger)?
3) Following the second question, in case the orgs (and the peers) are available before the channel creation can I join them all to the channel during the channel creation?

**Comment by nkaramolegos** [comment]
Also, in case I need to create a new channel for the available orgs and orderer nodes what should I change? Do I need I new network config file?

**Comment by nkaramolegos** [comment]
I am trying to setup a network with 3 orgs (2 peers each one) and 1 orderer org (1 orderer node at the beginning). I have installed/approved/commited  the chaincode in the peers but when I am running:
`kubectl hlf chaincode invoke --config=org1.yaml --user=adminOrg1 --peer=org1-peer0.default --chaincode=fabcar --channel=ch1 --fcn=initLedger -a '[]'`

I get the error:

`Error: error getting channel response for channel [ch1]: Discovery status Code: (11) UNKNOWN. Description: error received from Discovery Server: failed constructing descriptor for chaincodes:<name:"fabcar"`

I am attaching [threeOrgs_TwoPeers.txt](https://github.com/kfsoftware/hlf-operator/files/8263789/threeOrgs_TwoPeers.txt) the commands that I am running if you can take a look in case something I have missed. Of course, If I build the network I can format these file to use it as README for this particular use-case. I think It will be useful to other users of the project too.

**Comment by nkaramolegos** [comment]
Using the same approach I can set up a network with 2 orgs with 2 peers each one, and one orderer org with one orderer node but I can not do the same for 3 orgs with 2 peers each one.

**Comment by dviejokfs** [comment]
Hi @nkaramolegos 

I see this command as suspicious:
```bash
kubectl hlf channel generate --output=ch1.block --name=ch1 --organizations Org1MSP,Org2MSP,Org3MSP --ordererOrganizations OrdererMSP
```
It should be:
```bash
kubectl hlf channel generate --output=ch1.block --name=ch1 --organizations=Org1MSP --organizations=Org2MSP --organizations=Org3MSP --ordererOrganizations OrdererMSP
```
Try with this approach please and let us know :)

**Comment by nkaramolegos** [comment]
Nope, it does not solve the issue. Note that the argument for the organization is `StringSliceVarP` so in theory this can not create the problem. However, I tried your proposal without success. Any other ideas?

**Comment by dviejokfs** [comment]
I'm out of ideas right now, but there can be because:
- Package ID not installed in the peers
- Anchor peers not configured
- Consensus not working

Can you please paste the logs of the peers/orderers and send the configuration of the channel? you can inspect the channel with a command like the following:
```bash
kubectl hlf channel inspect --channel=demo --config=org1.yaml \
    --user=admin -p=org1-peer0.default > demo.json
```

**Comment by nkaramolegos** [comment]
Hi @dviejokfs 
* When I query the chaincode the `PACKADE_ID` in all peer is the same
* I have set as anchor peers the `peer0` of each three orgs
* Hmm I don't know how to verify that

The attach what you had asked
[org1_peer0.txt](https://github.com/kfsoftware/hlf-operator/files/8361851/org1_peer0.txt)
[org2_peer0.txt](https://github.com/kfsoftware/hlf-operator/files/8361853/org2_peer0.txt)
[org3_peer1.txt](https://github.com/kfsoftware/hlf-operator/files/8361854/org3_peer1.txt)
[ch1.txt](https://github.com/kfsoftware/hlf-operator/files/8361857/ch1.txt)

**Comment by nkaramolegos** [comment]
Hint If I set the policy to default and not `--policy="OR('Org1.peer', 'Org2.peer', 'Org3.peer')"` I have no problems.

Note that I am using hlf-operaror v1.5.0 (the v1.5.1 is not prebuild) and hlf-plugin v.1.5.1

**Comment by dviejokfs** [comment]
Hmm looking at the channel json, I see the the orgs are named:
- Org1MSP
- Org2MSP
- Org3MSP

And if the endorsement policy you're specifying:
- Org1
- Org2
- Org3

So it looks like the policy needs to be:
```bash
--policy="OR('Org1MSP.peer', 'Org2MSP.peer', 'Org3MSP.peer')"
```

@nkaramolegos  Can you test that policy?

**Comment by nkaramolegos** [comment]
I just tested. You are correct. I don't know how I miss it. Are you interested to integrate this script to the repository as extra example?

**Comment by dviejokfs** [comment]
Perfect, I'm glad it worked, I'm closing this issue @nkaramolegos
