### ISSUE TITLE
Chaincode as an external service

### ISSUE THREAD

**Issue by snitrama** [kfsoftware/hlf-operator#62]
Hi, thanks for the amazing work done in this project. Does the operator supports chaincode as an external service? 

I am having troubles understanding how we could customize the [existing instructions](https://kfsoftware.github.io/hlf-operator/docs/user-guide/install-chaincode) on how to do it. Does it requires configuring  an external builder with the scripts presented in the [HLF docs](https://hyperledger-fabric.readthedocs.io/en/release-2.4/cc_service.html)? Is there any example/docs on how to do this?

**Comment by dviejokfs** [comment]
Hi @snitrama 

External chaincode as a service will be supported in 1.6.0.

This PR #56 it's implementing this feature.

**Comment by snitrama** [comment]
How far away is it from completion and how can I contribute to it?

**Comment by dviejokfs** [comment]
25th of March maximum, I need to fix the tests which are failing, if you want to can take a look at that.

Though you can start using it by checking out that branch and following the instructions in the README.md which are updated to use the chaincode as an external service.

https://github.com/kfsoftware/hlf-operator/tree/feature/chaincode-as-a-service-crd

**Comment by snitrama** [comment]
While following the new instructions, executing:
```bash
kubectl hlf chaincode install --path=./asset-transfer-basic-external.tgz \
 --config=org1.yaml --language=golang --label=$CHAINCODE_LABEL --user=admin --peer=org1-peer0.default
```

Gives the following error:

`Error: Transaction processing for endorser [172.27.0.2:32208]: Chaincode status Code: (500) UNKNOWN. Description: failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker build is disabled`

Any idea on what may be causing this, or how can I debug it?

Note:
Installing non external chaincode works without issues:  
```
kubectl hlf chaincode install --path=./fixtures/chaincodes/fabcar/go \
     --config=org1.yaml --language=golang --label=fabcar --user=admin --peer=org1-peer0.default
```

**Comment by dviejokfs** [comment]
Hi @snitrama 

I think that problem is related to #63.

Will create 1.6.0-beta12 which should fix this issue.

**Comment by nkaramolegos** [comment]
The exact opposite [here](https://github.com/hyperledger-labs/hlf-operator/issues/89#issuecomment-1124836077) for version 1.6.4

**Comment by srinathln7** [comment]
Hi @snitrama  @nkaramolegos   By any chance, have you figured out how to solve the following error? 
```
Error: Transaction processing for endorser [172.27.0.2:32208]: Chaincode status Code: (500) UNKNOWN. Description: failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker build is disabled
```
Both internal and external chaincode installation poses the above problem. I use peer v2.4.4 from hyperledger fabric and hlf-operator v1.6.1 in KIND. Thank you.

**Comment by nkaramolegos** [comment]
Hi @srinathLN7 take  a look from [this](https://discord.com/channels/905194001349627914/967823782712594442/988820335099019384) message. I had never tried it but it may work. I had not time to search for the solution so I used CCAAS

**Comment by srinathln7** [comment]
@nkaramolegos  Thank you for your response. Even am trying it as CAAS but it doesn't work. Could you please tell me how you went about it?

**Comment by nkaramolegos** [comment]
@snitrama I followed the instructions of README. Note that you have to use a public (or private but it is a bit tricky) repository (like docker hub) to push your image or you kind local repository (that's what I use). Then in the `kubectl hlf externalchaincode sync` command you add your repository to` --image` argument.

For the kind local repository. I do the following:
1. Create a kind cluster using [this](https://kind.sigs.k8s.io/docs/user/local-registry/) script in order to create a kind local registry
2. Build your chaincode image as described [here](https://github.com/hyperledger/fabric-samples/tree/main/asset-transfer-basic/chaincode-external#running-the-asset-transfer-basic-external-service) `docker build ...`
3. As soon as you have the image built (see `docker images`) then follow the [using the registry](https://kind.sigs.k8s.io/docs/user/local-registry/#using-the-registry) steps.
4. Install chaincode as described in README (i.e `tar cfz ...`, `kubectl hlf chaincode install`) and then in the `kubectl hlf externalchaincode sync` command  use your kind registry to `image` argument (i.e `localhost:5001/your-chaincode-image-name:latest`)

@dviejokfs it may be good idea  to add these instructions in the README

**Comment by srinathln7** [comment]
@nkaramolegos I have the chaincode image in my local. Is it possible to sync it or it is must to upload the image to the kind registry?

**Comment by nkaramolegos** [comment]
> @nkaramolegos I have the chaincode image in my local. Is it possible to sync it or it is must to upload the image to the kind registry?

Yes you have to push it to local kind registry.

**Comment by srinathln7** [comment]
@nkaramolegos  Ha, my project requirement doesn't allow it. Is there no other way around it? Both my local installations as in the README.md with the local directory `k hlf chaincode install --path=./chaincode --config=network-config.yaml --language=$CC_LANG --label=$CC_NAME --user=admin --peer=org1-peer0.fabric` or using the `external.tgz` like `k hlf chaincode install --path=./chaincode/${CC_NAME}-external.tgz --config=network-config.yaml --language=$CC_LANG --label=$CC_NAME --user=admin --peer=org1-peer0.fabric` both fails with error `docker build disabled`.

**Comment by srinathLN7** [comment]
@nkaramolegos  If no way, thank you for your responses, and suggestions. Really appreciate!

**Comment by srinathln7** [comment]
@nkaramolegos  And finally managed to solve it. Please find my explanation here just in case you are interested - https://stackoverflow.com/questions/73100516/docker-build-is-disabled-error-when-installing-my-chaincode-on-hyperledger-fabri/73153204#73153204

Thank you for your help.

**Comment by srinathln7** [comment]
> @snitrama I followed the instructions of README. Note that you have to use a public (or private but it is a bit tricky) repository (like docker hub) to push your image or you kind local repository (that's what I use). Then in the `kubectl hlf externalchaincode sync` command you add your repository to` --image` argument.
> 
> For the kind local repository. I do the following:
> 
> 1. Create a kind cluster using [this](https://kind.sigs.k8s.io/docs/user/local-registry/) script in order to create a kind local registry
> 2. Build your chaincode image as described [here](https://github.com/hyperledger/fabric-samples/tree/main/asset-transfer-basic/chaincode-external#running-the-asset-transfer-basic-external-service) `docker build ...`
> 3. As soon as you have the image built (see `docker images`) then follow the [using the registry](https://kind.sigs.k8s.io/docs/user/local-registry/#using-the-registry) steps.
> 4. Install chaincode as described in README (i.e `tar cfz ...`, `kubectl hlf chaincode install`) and then in the `kubectl hlf externalchaincode sync` command  use your kind registry to `image` argument (i.e `localhost:5001/your-chaincode-image-name:latest`)
> 
> @dviejokfs it may be good idea to add these instructions in the README

Thanks, this was very helpful.

**Comment by dviejokfs** [comment]
> 4\. Install chaincode as described in README (i.e `tar cfz ...`, `kubectl hlf chaincode install`) and then in the `kubectl hlf externalchaincode sync` command  use your kind registry to `image` argument (i.e `localhost:5001/your-chaincode-image-name:latest`)

Yeah, this will be added to the documentation, this is very useful 👍
