### ISSUE TITLE
HLF peer Image always point to default value

### ISSUE THREAD

**Issue by handysama** [kfsoftware/hlf-operator#63]
Recently i update and tried the latest example in README and notice the peer image got changed to
`export PEER_IMAGE=hyperledger/fabric-peer` from `export PEER_IMAGE=quay.io/kfsoftware/fabric-peer`

https://github.com/kfsoftware/hlf-operator/pull/56/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R85

Based on these lines, it seem validate will always return ok (nil), and value overwritten with default value.
Is it intended behaviour?

https://github.com/kfsoftware/hlf-operator/blob/bfdd964b140c4f9d9e52a9c8a30dfe6fd162260c/kubectl-hlf/cmd/peer/create.go#L52-L55

I still can make example in README run by using old PEER_VERSION and point to old PEER_IMAGE.

Thank you for providing great example for Hyperledger setup

**Comment by dviejokfs** [comment]
Yeah, you are right, @handysama.

I just created PR #64 that should fix this issue before releasing 1.6.0

**Comment by handysama** [comment]
Thanks a lots :+1:
