### ISSUE TITLE
Usage with pluggable consensus service

### ISSUE THREAD

**Issue by nileshmali** [kfsoftware/hlf-operator#67]
First of all thanks for creating an operator as it makes our life easier to manage hyperledger fabric.

Is it possible to use this with pluggable consensus service Ex. Hedera Hashgraph?
Any documentation or pointers would be useful.

Thanks Again

**Comment by dviejokfs** [comment]
Hi @nileshmali 

Thank you for your consideration.

In theory, it's possible, since Hyperledger Fabric supports pluggable consensus, though, there need to be instructions on how to integrate Hedera Hashgraph, and searching through the internet I cannot find any practical example.

Could you provide some example?

**Comment by nileshmali** [comment]
Hi @dviejokfs,
Thanks for your response.
I found this example https://github.com/hyperledger-labs/pluggable-hcs 
The `first-network` example in the above repository contains a docker-compose sample.

Thanks

**Comment by nileshmali** [comment]
Any pointers?

**Comment by dviejokfs** [comment]
@nileshmali, thank you for being patient on this.

Changing the consensus would need another way to reach a consensus that is not clear and, more importantly, not supported. Furthermore, the project you mentioned has been archived meaning is not being maintained anymore.

I recommend you stick with the RAFT consensus for the ordering service.

If there are enough people/companies interested in this, we can reconsider when that time comes.

**Comment by nileshmali** [comment]
@dviejokfs Thanks for your response.
Anyways, I will be trying with https://hyperledgendary.github.io/unstable-fabric-docs/pluggable_endorsement_and_validation.html#pluggable-endorsement-and-validation-logic which should work out of the box.
