### ISSUE TITLE
Getting started errors

### ISSUE THREAD

**Issue by ZappaBoy** [kfsoftware/hlf-operator#69]
Hi all,
I'm following the "Getting started" and I noticed that you added the "chaincode as a service" feature of Hyperledger Fabric. 
I noticed that using the default `PEER_VERSION=2.4.1` and `ORDERER_VERSION=2.4.1` the peer creation doesn't work. I think that this is because there is no version `2.4.1`  in your `quay.io/kfsoftware/fabric-peer` (checked at: https://quay.io/repository/kfsoftware/fabric-peer?tab=tags). So I tried with `PEER_VERSION=2.4.0-v0.0.4` and the peer creation worked. 

After that, I noticed that the [Install chaincode section](https://github.com/kfsoftware/hlf-operator#install-a-chaincode) has some problems: 
- Both `code.tar.gz` `asset-transfer-basic-external.tgz` are not defined well;
- `asset-transfer-basic-external.tgz` does not exist at all; 
- I can't understand where and how to install my chaincode.

**Comment by dviejokfs** [comment]
Hi @ZappaBoy 

This is most likely because you need to upgrade the kubectl plugin, I ran similar issues when using the previous version, try:
```bash
 kubectl krew upgrade hlf   
```

About the chaincode, the recent getting started docs refer to using chaincode as an external service, can you check the running external chaincodes:

```bash
 kubectl get fabricchaincodes.hlf.kungfusoftware.es
```

**Comment by ZappaBoy** [comment]
@dviejokfs Thanks for the answer and please excuse me for the delay. 
I can confirm that upgrading `hlf` with `krew` works and fixed both peer/orderer version and chaincode installation issues.

About the chaincode as an external service can you explain how to create your chaincode external service (i think using `kfsoftware/chaincode-external` image)?

**Comment by dviejokfs** [comment]
That image is a default one in order to deploy a chaincode for the getting started, if you want to deploy your own chaincode you need to build your own image and deploy it.

You can take a look at the example from fabric-samples, I think is called external chaincode.

More documentation about this will be added to the project soon

**Comment by ZappaBoy** [comment]
Ok, it's clear, i thought it was some particular image. 

Thanks a lot

**Comment by dviejokfs** [comment]
Closing issue at it seems the problem has been solved
