### ISSUE TITLE
Request for adding a subset of the availables orderers in the new channel

### ISSUE THREAD

**Issue by nkaramolegos** [kfsoftware/hlf-operator#70]
Hello, I would like to request a new feature. When a new channel is created then all the available orderers of the cluster are joining the channel. It would be good the specify the orderers joining the channel so you can have a subset of the available orderers.

**Comment by dviejokfs** [comment]
Hi @nkaramolegos 

We can remove the parameter for the orderer join in order to join all orderers in the cluster.

This will be implemented in the next version this week.

**Comment by nkaramolegos** [comment]
Hi @dviejokfs What is the status of the integration?

**Comment by dviejokfs** [comment]
Hi @nkaramolegos, sorry for the wait
I created PR #82 to implement this feature.
