### ISSUE TITLE
 hlf ca create error on hlf plugin v1.6.0 

### ISSUE THREAD

**Issue by alphalykos** [kfsoftware/hlf-operator#71]
Hi @all,

When I'm using hlf plugin v1.6.0 and creating CA, I'm getting following error:

```
Error: FabricCA.hlf.kungfusoftware.es "org1-ca" is invalid: spec.image: Invalid value: "": spec.image in body should be at least 1 chars long
```

I checked another machine with hlf plugin v1.5.1.t  Iwas working fine. 

Works fine as below with v1.4.0 too.
```
kubectl krew index add slot-machine-games https://github.com/eurogame/krew-index
kubectl krew install slot-machine-games/hlf
```

**Comment by dviejokfs** [comment]
Hi @alphalykos 

Can you try upgrading the kubectl hlf plugin? It should upgrade you to the v1.6.1 which fixes this.

When this PR is merged: https://github.com/kubernetes-sigs/krew-index/pull/2170

**Comment by handysama** [comment]
This issue related to https://github.com/kfsoftware/hlf-operator/pull/64#issuecomment-1077184430

As i mentioned when you remove default override, ca doesnt have default which cause error when you pass empty param.

**Comment by dviejokfs** [comment]
@handysama 

I just pushed a new version, 1.6.2, opened a new PR: https://github.com/kubernetes-sigs/krew-index/pull/2187

Try updating the kubectl plugin and execute this step again.

**Comment by handysama** [comment]
@dviejokfs it works fine here. Thanks for the patch.
