### ISSUE TITLE
Replace kungfusoftware.es with something else

### ISSUE THREAD

**Issue by nkaramolegos** [kfsoftware/hlf-operator#72]
In commands like `kubectl wait --timeout=180s --for=condition=Running fabricorderernodes.hlf.kungfusoftware.es --all` I would like to replace the kungfusoftware.es with an another name. Can I do that? What I have to change?

**Comment by dviejokfs** [comment]
These commands reference the CRD name, and `kungfusoftware.es` can only be changed if you fork this repository and replace it with the name you like.

Just out of curiosity, can you give more information about the problem and then we can check how we can solve it?

Thanks

**Comment by nkaramolegos** [comment]
Nothing special. I would like to change the name to something more familiar to my deployment. But Ok. There is no problem

**Comment by nkaramolegos** [comment]
So how can I compile and use the operator without using the ready to be deployed helm charts? I mean how can I download the code and then change the `kungfusoftware.es` to something else and compile the code and make the deployment of the network?
