### ISSUE TITLE
Multi cluster network setup

### ISSUE THREAD

**Issue by khazley1** [kfsoftware/hlf-operator#73]
Hey, I am curious if it is possible to create a multi cluster network using hlf-operator. If it is, what are the steps to achieve it?

**Comment by dviejokfs** [comment]
`hlf-operator` runs in a Kubernetes cluster, if you want to operate in multiple clusters you need to deploy the operator in all the clusters you want to use.

Domains need to be set up, you can take a look on how to set up Istio and expose your peers: 
https://kfsoftware.github.io/hlf-operator/docs/operator-guide/istio

**Comment by khazley1** [comment]
Perfect, I managed to set it up, thank you for help!
