### ISSUE TITLE
[Inspect] two namespaces dumped into single ccp

### ISSUE THREAD

**Issue by rrozek** [kfsoftware/hlf-operator#77]
Hi,
i figured out generating ccp via `kubectl hlf inspect` has no way to pass namespace param to limit the scope. On my cluster i have more then one HL instance in separate namespaces and by coincidence i have orgs which have the same name (namespace1 Org1MSP, namespace2 Org1MSP)
then when i run
```
kubectl hlf inspect --output resources/Org1MSP/ccp.yaml -o Org1MSP --internal
```
i get results from both namespaces and need to modify the resulting ccp manually.

passing
```
kubectl hlf inspect --output resources/Org1MSP/ccp.yaml -o Org1MSP --internal --namespace=namespace1
```
throws `Error: unknown flag: --namespace`

Now that i think about it, is it possible that the two HL deployments will interfere each other somehow? ... I guess its possible...

**Comment by dviejokfs** [comment]
Hi @rrozek 

I just created the PR #83 that implements this issue.

**Comment by dviejokfs** [comment]
Implemented
