### ISSUE TITLE
Creating an orderer using a remote CA

### ISSUE THREAD

**Issue by Wojciechowski-Marcin** [kfsoftware/hlf-operator#84]
Hello,

I am working on a multi cluster setup using HLF Operator and Istio with 3 CAs - org1-ca (cluster1), orderer-ca (cluster1), org2-ca (cluster2).

So far deployment of peers on both clusters and an orderer on cluster1 was fine, I managed to join them in a channel and they seem to communicate just fine, but now I would like to create an orderer on cluster2, using the orderer-ca from cluster1, but I get an error that CA with given name is not found on the cluster.

Is that even possible to create a network like this with HLF Operator?

**Comment by dviejokfs** [comment]
Hi @Wojciechowski-Marcin 

Yes, CA needs to be exposed using Istio: https://labs.hyperledger.org/hlf-operator/docs/operator-guide/istio

After that, you'll need to manually modify the enrollment cahost and caport of the peer and orderer.

**Comment by Wojciechowski-Marcin** [comment]
Thank you for the tip, it helped me solve the problem

For anyone with similar problem in the future, cahost should be the domain of the CA, caport should be port of the istio gateway (443 by default) and catls.cacert needs to be changed, it worked when I copied the value from orderer on cluster1.
