### ISSUE TITLE
important questions about the operator and the plugin

### ISSUE THREAD

**Issue by nkaramolegos** [kfsoftware/hlf-operator#89]
Hello, Some things are not well documented so I have a couple of questions which I believe will help everyone.
1. The latest version of hlf plugin is the 1.6.4 while of the operator (in helm charts) is the 1.6.1. Are these two version compatible? Is there any strict relation between the versions of the plugin and operator? 
2. If I clone the main repository I assume that the uploaded operator is fully compatible with the corresponding  uploaded plugin. I know how to build the plugin but how can I build the operator and how can I apply it to my k8s cluster without using the common `helm install hlf-operator -f values.yaml --version=1.6.1 kfs/hlf-operator` command
3. I had been using version 1.5.1 for both operator and plugin and the images versions of peer and orderer were 
```
export PEER_IMAGE=quay.io/kfsoftware/fabric-peer
export PEER_VERSION=2.3.2-v0
export ORDERER_IMAGE=hyperledger/fabric-orderer
export ORDERER_VERSION=2.3.2
```
The network was perfect. Now I have to jump to latest version of plugin and operator but I want to use the same version of peers and orderer. However, when I am running `kubectl hlf chaincode install --path=./chaincodes/fabcar/go --config=org1.yaml --language=golang --label=fabcar --user=$ORG1_ADMIN_USER --peer=org1-peer0.default &
` I am getting the error: _could not build chaincode: docker build failed: docker build is disabled_ . Same for version 2.4.3. Should I deploy the chaincode only [as a service](https://github.com/hyperledger-labs/hlf-operator#install-a-chaincode)?
4. Whenever the chaincode is installed [as a service](https://github.com/hyperledger-labs/hlf-operator#install-a-chaincode) where is the folder with the code (needed to be build) of the chaincode? 
5. What is the difference between the plugins commands channel create and generate?
6. In the latest version if I use `kubectl hlf channel generate --output=ch2.block --name=ch2 --organizations Org1MSP,Org2MSP,Org3MSP --ordererOrganizations OrdererMSP --consenterNodes ordnode-2
` only the ordnode-2 will be used as consenter is the new channel. Correct? If yes, I have not to run `kubectl hlf channel consenter add ` and `kubectl hlf channel update` commands afterward.

**Comment by dviejokfs** [comment]
1. Version of HLF helm chart is compatible, since there's no change in the CRDs
2. The helm chart in this repo for the operator is outdated, it must be removed in the next version
3. For the new version, I recommend you to use the latest version for fabric-peer, since the latest instructions are aligned with the chaincode as an external service, which is the recommended and since Hyperledger Fabric 2.4


@nkaramolegos  for more info, could you join the Hyperledger discord and we can comment in the `hlf-operator` channel? This way we can have faster conversations and responses

https://discord.com/channels/905194001349627914/967823782712594442

**Comment by nkaramolegos** [comment]
I would like to use plugin version 1.6.4 with the operator 1.6.1 which are compatible as you said with the 2.3.2 version of peer and orderer and without chaincode as a service. But whenever I run `kubectl hlf chaincode install --path=./chaincodes/fabcar/go --config=org1.yaml --language=golang --label=fabcar --user=$ORG1_ADMIN_USER --peer=org1-peer0.default` I get  _could not build chaincode: docker build failed: docker build is disabled_. Why that? Note that I can use the hlf version 1.5.1 with the 2.4.1 peer and orderer images without deploying CaaS.

**Comment by srinathln7** [comment]
> I would like to use plugin version 1.6.4 with the operator 1.6.1 which are compatible as you said with the 2.3.2 version of peer and orderer and without chaincode as a service. But whenever I run `kubectl hlf chaincode install --path=./chaincodes/fabcar/go --config=org1.yaml --language=golang --label=fabcar --user=$ORG1_ADMIN_USER --peer=org1-peer0.default` I get _could not build chaincode: docker build failed: docker build is disabled_. Why that? Note that I can use the hlf version 1.5.1 with the 2.4.1 peer and orderer images without deploying CaaS.

https://stackoverflow.com/questions/73100516/docker-build-is-disabled-error-when-installing-my-chaincode-on-hyperledger-fabri/73153204#73153204
