### ISSUE TITLE
Modify inspect command to filter by orderer

### ISSUE THREAD

**Issue by nkaramolegos** [kfsoftware/hlf-operator#93]
If in the channel has joined a subset of the cluster available orderers it would be good idea to modify the inspect command in order to filter by namespace or orderer names

**Comment by nkaramolegos** [comment]
How is this going?

**Comment by dviejokfs** [comment]
@nkaramolegos  Implemented in v1.7.0-beta3, waiting to test the [https://github.com/hyperledger-labs/fabric-operations-console](https://github.com/hyperledger-labs/fabric-operations-console) CRD to release v1.7.0


https://github.com/hyperledger-labs/hlf-operator/releases/tag/v1.7.0-beta3

**Comment by nkaramolegos** [comment]
Nice. What is the relation of the operator with the fabric-operations-console?

**Comment by dviejokfs** [comment]
Implemented in 1.7.0
