### ISSUE TITLE
Enroll failure!  CA Register - from my local pc to AWS EKS Cluster running on private subnet

### ISSUE THREAD

**Issue by jaljaivikbazaar** [kfsoftware/hlf-operator#97]
I am getting this error while tring to deploy it on AWS EKS Cluster 

```
@MacBook-Pro kube-manifests % kubectl hlf ca register --name=org1-ca --user=org1-peer1 --secret=peerpw --type=peer --enroll-id enroll --enroll-secret=enrollpw --mspid=Org1MSP --namespace=fabric
 [fabsdk/fab] 2022/05/29 07:16:39 UTC - n/a -> INFO TLS Enabled
 [fabsdk/fab] 2022/05/29 07:16:39 UTC - n/a -> INFO generating key: &{A:ecdsa S:256}
 [fabsdk/fab] 2022/05/29 07:16:39 UTC - logbridge.(*cLogger).Info -> INFO encoded CSR
Error: enroll failed: enroll failed: POST failure of request: POST https://192.168.151.72:30371/enroll
{
  "hosts": null,
  "certificate_request": "-----BEGIN CERTIFICATE REQUEST-----\nMIIBAjCBqQIBADARMQ8wDQYDVQQDEwZlbnJvbGwwWTATBgcqhkjOPQIBBggqhkjO\nXXXXnvehpbO3z7Vosyt3yQFS4fmDyWQ1Smw==\n-----END CERTIFICATE REQUEST-----\n",
  "profile": "",
  "crl_override": "",
  "label": "",
  "NotBefore": "0001-01-01T00:00:00Z",
  "NotAfter": "0001-01-01T00:00:00Z",
  "ReturnPrecert": false,
  "CAName": ""
}: Post "https://192.168.151.72:30371/enroll": dial tcp 192.168.151.72:30371: connect: operation timed out
```

I tried to access the endpoint directly from my local pc, then it shows up error

```
@MacBook-Pro network % curl https://192.168.151.72:30371/cainfo -k
curl: (28) Failed to connect to 192.168.151.72 port 30371 after 75007 ms: Operation timed out
```

I tried to create a Curl-Pod on my AWS EKS Cluster Private Subnet and then tried to access the CA Ip, it worked then.

```
@MacBook-Pro kube-manifests % kubectl apply -f 03-curl-pod.yml -n fabric
pod/curl-pod created
MacBook-Pro kube-manifests % kubectl exec -it curl-pod -n fabric -- sh
/ $ curl https://192.168.151.72:30371/cainfo -k
{
  "result": {
    "CAName": "ca",
    "CAChain": "LS0tLXXXXXXXXXXLS0tLS0K",
    "IssuerPublicKey": "CgJPVQoEUXXXXXSakQcGgtG/z",
    "IssuerRevocationPublicKey": "LS0tLS1CRUXXXXXXXRVktLS0tLQo=",
    "Version": "1.4.9"
  },
  "errors": [],
  "messages": [],
  "success": true
}
```

What do you suggest to overcome this issue so that I could be able to deploy the HLF Network on a AWS EKS Cluster running on a Private Subnet

Thanks in advance

**Comment by dviejokfs** [comment]
Hi @jaljaivikbazaar 

Since the IP of the Kubernetes nodes is not accessible from your client machine, you need to deploy it with Istio, with a public IP and DNS domains pointing to the public IP you provisioned in AWS:

[https://labs.hyperledger.org/hlf-operator/docs/operator-guide/istio](https://labs.hyperledger.org/hlf-operator/docs/operator-guide/istio)

**Comment by sapient** [comment]
Hi @jaljaivikbazaar, I had the same problem a few weeks ago, I initially fixed it by just adding a --hosts=xxx flag to the ca creation, but I had more problems later when deploying peers and orderers when they ignored the hostname for the CA and tried to enroll via the workers ip again. 

I later figured out that my VPC inbound rules blocked all comms to the k8s worker nodes, the only solution I have found so far is to open the ports in the VPC, which allows all the internal comms for enrollment etc to work fine.

**Comment by jaljaivikbazaar** [comment]
I worked on it and now I have got it fix. ```istio``` service generated the External Public Ip. I just have to create new DNS ```A Records``` with this Public IP. Rest of the commands were almost same.

**Comment by regmicmahesh** [comment]
Hi @jaljaivikbazaar . Can we connect further to discuss on this? I'm facing the same issue.
